### ISSUE TITLE
Recommended unit testing practices?

### ISSUE THREAD

**Issue by aorumbayev** [aio-libs/aiokafka#561]
Hi all, 

I was wondering what are the recommended unit testing best practices when using aiokafka?

Can anyone provide unit test samples for AIOConsumers or AIOProducers ?

Does library provide mocked test sessions to imitate the interactions between producer and consumers ? I really want to avoid relying on real Kafka instance for unit testing.

**Comment by tvoinarovskyi** [comment]
> I was wondering what are the recommended unit testing best practices when using aiokafka?

I prefer testing on real functional scenarios and would mostly just work with a real instance. It's in docker, works quite fast, tests are not perfect, but stable enough (some cases coverage can go ~0.1% because of some racing).
See https://github.com/aio-libs/aiokafka/blob/master/tests/test_consumer.py#L1889 for example.

> Does library provide mocked test sessions to imitate the interactions between producer and consumers ? I really want to avoid relying on real Kafka instance for unit testing.

Sorry, we don't have mocked sessions, tend to use the real instance in most cases. I feel that real scenarios are better because aiokafka is a project, that is still a bit flaky on internals, they change as we tend to move away from Java code and kafka-python dependency. It helps to write tests from public interface so that we don't rewrite tests too often.

If you feel like you need a concrete guide, could you send me a nice documentation example so I can model a contribution page or something?

And could you share what scenario do you want to test exactly? I do mock testing at https://github.com/aio-libs/aiokafka/blob/master/tests/test_sender.py. The code was written to be better testable by unit scenarios and I found the style to be quite convenient.

**Comment by tvoinarovskyi** [comment]
Hope it helped to answer the question.

**Comment by wowpoppy** [comment]
Implementing a test context would be more preferable since testing with a real instance is impossible with multiple test workers: I have two of ten tests failed due to messages being consumed by another test worker and I have no idea how to deal with it but declare separate topics for test purposes only
