### ISSUE TITLE
Timeout on metadata request to broker

### ISSUE THREAD

**Issue by MichalMazurek** [aio-libs/aiokafka#576]
Hi,

I have multiple brokers and one of them is acting up and I get TimeoutError on this line:

https://github.com/aio-libs/aiokafka/blob/96159c6f74873005d0c123b07ec80fb1756f6c8a/aiokafka/client.py#L204

I can connect to broker but then connection stalls on sending the metadata request, a TimeoutError exception handling here would solve the issue. Kafka-python handles it, it takes some time for the timeout to kick on but it just moves to the other broker.

I can make a pull request for it, just let me know if do you think this might solve the issue?

All the best

**Comment by tvoinarovskyi** [comment]
Well, it was intensional, that initial connect would not have delegated connect and would wait up to timeout on connection (we want a clear error if we can't reach the cluster right away). The problem is that it does not try out other connections. This part is actually quite safe to change as it is a blocking initial connect with no race conditioning, you can change it how you see fit in a PR as long as tests pass. Another idea would be to change this step to perform bootstrap in parallel to all nodes and join those coroutines.
PR would be great, feel free to reach out if you need any help with it.

**Comment by MichalMazurek** [comment]
I was thinking about it, that it could be done in parallel, but I thought at least this fix would solve the issue. I would love to do it in parallel, I'll do the first PR to fix the issue and after it's accepted I can do the parallel one :)

**Comment by MichalMazurek** [comment]
Hi just wanted to bump it as this is ready :)

**Comment by tvoinarovskyi** [comment]
Sorry for the long one, done
