### ISSUE TITLE
Add SASL Plain support

### ISSUE THREAD

**Issue by tvoinarovskyi** [aio-libs/aiokafka#84]
kafka-python already has support for that, so it shouldn't be that hard.

**Comment by cyrbil** [comment]
Would really like to see it implemented in an async fashion :)
Is this planned for a next future ? If not, could you point out where and how it could be implemented, so I might dive in this feature ?

**Comment by castarco** [comment]
@cyrbil I'm sorry, our prioritization changed and I had to stop developing that feature :( .

**Comment by fisuk** [comment]
#386 
@cyrbil @tvoinarovskyi 

Seems like I got these patches working with the latest master with some caveats :

Consumer:
- In the beginning I do get a bunch of failed authentications after which it succeeds. 
- If the connection fails at some point, reconnecting fails (and from short testing, it always fails at some point), 
- If a consumer cannot find a topic on the broker, it attempts to create that topic which in turn requires permissions to create topics and if the consumer doesn't have those permissions, the consumer is left in an reconnect loop with no apparent reason as to why it's failing. Not sure why the consumer tries to create the non-existing topic, but that might be because I have automatic creation of topics enabled on the broker(s).

Producer:
- After adding SASL related arguments to the AIOKafkaProducer class, rudimentary testing shows that producing works with no bigger problems. Same as with the consumer, in the beginning there's a failed authentication (broker response being Error 33).

Kafka broker version: 2.0
Python: 3.6.6

**Comment by tvoinarovskyi** [comment]
Protocol changes in #464 should be good now. Will need to work on all exception handling in Producer and Consumer.
